<a href="https://colab.research.google.com/github/Dylan1156/DSC.110_test/blob/main/week5_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/osoliman/DSC110/refs/heads/main/Datasets/nhanes_final.csv')

In [ ]:
df

,id,gender,age,race_ethnicity,education,bmi,height_cm,systolic_bp,has_diabetes,hba1c,fasting_glucose
0,130378.0,1.0,43.0,6.0,5.0,27.0,179.5,135.0,2.0,5.6,113.0
1,130379.0,1.0,66.0,3.0,5.0,33.5,174.2,121.0,2.0,5.6,99.0
2,130380.0,2.0,44.0,2.0,3.0,29.7,152.9,111.0,1.0,6.2,156.0
3,130381.0,2.0,5.0,7.0,NaN,23.8,120.1,NaN,2.0,NaN,NaN
4,130382.0,1.0,2.0,3.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
11928,142306.0,1.0,9.0,2.0,NaN,15.4,128.0,NaN,2.0,NaN,NaN
11929,142307.0,2.0,49.0,4.0,5.0,NaN,143.8,127.0,1.0,6.2,NaN
11930,142308.0,1.0,50.0,2.0,4.0,26.4,173.3,106.0,2.0,NaN,NaN
11931,142309.0,1.0,40.0,2.0,4.0,25.5,179.1,127.0,2.0,5.2,96.0
11932,142310.0,2.0,80.0,3.0,3.0,27.6,161.7,128.0,2.0,5.3,NaN

In [ ]:
df.head(10)

,id,gender,age,race_ethnicity,education,bmi,height_cm,systolic_bp,has_diabetes,hba1c,fasting_glucose
0,130378.0,1.0,43.0,6.0,5.0,27.0,179.5,135.0,2.0,5.6,113.0
1,130379.0,1.0,66.0,3.0,5.0,33.5,174.2,121.0,2.0,5.6,99.0
2,130380.0,2.0,44.0,2.0,3.0,29.7,152.9,111.0,1.0,6.2,156.0
3,130381.0,2.0,5.0,7.0,NaN,23.8,120.1,NaN,2.0,NaN,NaN
4,130382.0,1.0,2.0,3.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN
5,130383.0,2.0,3.0,2.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN
6,130384.0,1.0,43.0,1.0,2.0,NaN,NaN,NaN,2.0,NaN,NaN
7,130385.0,2.0,65.0,3.0,3.0,NaN,NaN,NaN,2.0,NaN,NaN
8,130386.0,1.0,34.0,1.0,4.0,30.2,173.3,110.0,2.0,5.1,100.0
9,130387.0,2.0,68.0,3.0,5.0,42.6,155.9,143.0,2.0,5.9,NaN

In [ ]:
df.tail(1)

,id,gender,age,race_ethnicity,education,bmi,height_cm,systolic_bp,has_diabetes,hba1c,fasting_glucose
11932,142310.0,2.0,80.0,3.0,3.0,27.6,161.7,128.0,2.0,5.3,NaN

In [ ]:
df.shape

(11933, 11)

In [ ]:
df.shape[0]

11933

In [ ]:
print(f'The number of rows in our dataframe is {df.shape[0]} rows')
print(f'The number of columns in our dataframe is {df.shape[1]} columns')

The number of rows in our dataframe is 11933 rows
The number of columns in our dataframe is 11 columns

In [ ]:
df['age'].head()

0    43.0
1    66.0
2    44.0
3     5.0
4     2.0
Name: age, dtype: float64

In [ ]:
1+1==2

True

In [ ]:
1+1==3

False

In [ ]:
int(1+1==2)

1

In [ ]:
int(1+1==3)

0

In [ ]:
int(False)

0

# **Data Cleaning**

In [ ]:
#Here is our comment
df.isna().sum()

id                    0
gender                0
age                   0
race_ethnicity        0
education          4139
bmi                3462
height_cm          3434
systolic_bp        4416
has_diabetes        193
hba1c              5218
fasting_glucose    8261
dtype: int64

In [ ]:
df.isna().mean() * 100

id                  0.000000
gender              0.000000
age                 0.000000
race_ethnicity      0.000000
education          34.685326
bmi                29.011984
height_cm          28.777340
systolic_bp        37.006620
has_diabetes        1.617364
hba1c              43.727478
fasting_glucose    69.228191
dtype: float64

In [ ]:
df_clean = df.dropna(subset=['has_diabetes']).copy()

In [ ]:
df_clean.isna().mean() * 100

id                  0.000000
gender              0.000000
age                 0.000000
race_ethnicity      0.000000
education          33.611584
bmi                27.844974
height_cm          27.606474
systolic_bp        35.971039
has_diabetes        0.000000
hba1c              42.802385
fasting_glucose    68.722317
dtype: float64

In [ ]:
df_clean.shape

(11740, 11)

In [ ]:
mean_bp = df_clean['systolic_bp'].mean()
print(mean_bp)

119.28854596248503

In [ ]:
df_clean['systolic_bp'] = df_clean['systolic_bp'].fillna(mean_bp)

In [ ]:
df_clean['systolic_bp'].isna().sum()

np.int64(0)

Transform Variables

In [ ]:
# Converting numerical to categorical
# Create BMI categories
df['bmi_category'] = pd.cut(df['bmi'],
                             bins=[0, 18.5, 25, 30, 100],
                             labels=['Underweight', 'Normal', 'Overweight', 'Obese'])

In [ ]:
df['bmi_category'].head()

0    Overweight
1         Obese
2    Overweight
3        Normal
4           NaN
Name: bmi_category, dtype: category
Categories (4, object): ['Underweight' < 'Normal' < 'Overweight' < 'Obese']

In [ ]:
df['bmi_category'].value_counts()

bmi_category
Obese          2666
Normal         2400
Overweight     2189
Underweight    1216
Name: count, dtype: int64

Categorical Variable Transformation

In [ ]:
df['education'].head()

0    5.0
1    5.0
2    3.0
3    NaN
4    NaN
Name: education, dtype: float64

In [ ]:
education_map = {
    1: 'Less than 9th grade',
    2: '9-11th grade',
    3: 'High school grad',
    4: 'Some college or AA degree',
    5: 'College graduate',
    9: 'Do not know',
    'nan': 'Missing'
}

In [ ]:
education_map['1.0']

'Less than 9th grade'

In [ ]:
df['education_label'] = df['education'].map(education_map)
df['education_label'].value_counts()

education_label
College graduate             2625
Some college or AA degree    2370
High school grad             1749
9-11th grade                  666
Less than 9th grade           373
Do not know                    11
Name: count, dtype: int64

In [ ]:
df['education_label'].value_counts()

Series([], Name: count, dtype: int64)

In [ ]:
df['education'].unique()

array([ 5.,  3., nan,  2.,  4.,  1.,  9.])

In [ ]:
df['education'].dtype

dtype('float64')

# **Data Summarization**

In [ ]:
# Numberical values
avg_age = df['age'].mean()
print(f'The average age in our data is {round(avg_age,0)}')

The average age in our data is 38.0

In [ ]:
std_age = df['age'].std()
print(f'The standard devation for age in our data is {round(std_age,0)}')

The standard devation for age in our data is 26.0

In [ ]:
df['age'].median()

37.0

In [ ]:
df['age'].quantile([0.25, 0.75])

0.25    13.0
0.75    62.0
Name: age, dtype: float64

In [ ]:
df['age'].mode()

0    80.0
Name: age, dtype: float64

In [ ]:
df['age'].describe()

count    1.193300e+04
mean     3.831786e+01
std      2.560199e+01
min      5.397605e-79
25%      1.300000e+01
50%      3.700000e+01
75%      6.200000e+01
max      8.000000e+01
Name: age, dtype: float64

Summarizing categorical variable

In [ ]:
# Frequency
df['gender'].value_counts()

gender
2.0    6358
1.0    5575
Name: count, dtype: int64

In [ ]:
pd.crosstab(df['has_diabetes'], df['bmi_category'])

bmi_category  Underweight  Normal  Overweight  Obese
has_diabetes
1.0                     4     109         233    504
2.0                  1211    2251        1886   2042
3.0                     0      39          70    120
9.0                     1       1           0      0

In [ ]:
pd.crosstab(df['has_diabetes'], df['bmi_category'], normalize='index') * 100

bmi_category  Underweight     Normal  Overweight      Obese
has_diabetes
1.0              0.470588  12.823529   27.411765  59.294118
2.0             16.387009  30.460081   25.520974  27.631935
3.0              0.000000  17.030568   30.567686  52.401747
9.0             50.000000  50.000000    0.000000   0.000000

In [ ]:
# df.groupby('grouping_variable')['numeric_variable'].calculation()
df.groupby('has_diabetes')['bmi'].mean()

has_diabetes
1.0    32.981412
2.0    26.439797
3.0    32.068559
9.0    19.250000
Name: bmi, dtype: float64